"""enerji donusum katsayilari

Kullanici tanimli enerji icerigi katsayisi: 1 <enerji turu birimi> = factor GJ.
Bir donem icin valid_from <= donem tarihi kosulunu saglayan en yeni kayit
kullanilir.

Revision ID: 34855fc1f004
Revises: 357a2b184ffc
Create Date: 2026-09-17 05:56:44.909522
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '34855fc1f004'
down_revision: str | None = '357a2b184ffc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy_type_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['energy_type_id'], ['energy_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('energy_type_id', 'valid_from')
    )
    with op.batch_alter_table('energy_conversion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_conversion_valid_from'), ['valid_from'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_conversion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_conversion_valid_from'))

    op.drop_table('energy_conversion')
    # ### end Alembic commands ###
