"""dogrudan tuketim tablosu

Revision ID: 357a2b184ffc
Revises: 26b1da15eda9
Create Date: 2026-09-17 05:33:23.793503
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '357a2b184ffc'
down_revision: str | None = '26b1da15eda9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('energy_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['energy_type_id'], ['energy_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_date', 'energy_type_id')
    )
    with op.batch_alter_table('direct_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_consumption_period_date'), ['period_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_consumption_period_date'))

    op.drop_table('direct_consumption')
    # ### end Alembic commands ###
