"""ilk sema

Revision ID: 730452d9c554
Revises: 
Create Date: 2026-09-16 18:40:47.639126
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '730452d9c554'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('energy_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_production_date'), ['production_date'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('energy_type_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=60), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['energy_type_id'], ['energy_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('energy_type_id', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['energy_type_id'], ['energy_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month', 'energy_type_id')
    )
    op.create_table('meter_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('index_value', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'reading_date')
    )
    with op.batch_alter_table('meter_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_reading_reading_date'), ['reading_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_reading_reading_date'))

    op.drop_table('meter_reading')
    op.drop_table('target')
    op.drop_table('meter')
    op.drop_table('settings')
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_production_date'))

    op.drop_table('production')
    op.drop_table('energy_type')
    op.drop_table('department')
    # ### end Alembic commands ###
